- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
- name: Ensure fail2ban is enabled and running
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
- name: Deploy custom fail2ban jail.local
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    mode: '0644'
    content: |
      [DEFAULT]
      bantime  = 1h
      findtime  = 10m
      maxretry = 5

      [sshd]
      enabled = true
      port    = ssh
      logpath = %(sshd_log)s
      backend = systemd
  notify: Restart fail2ban
