- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled
    policy: deny

- name: Apply firewall rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
  loop: "{{ firewall_rules }}"
  when: firewall_rules is defined
