- name: Ensure Linstor services are enabled and started
  ansible.builtin.systemd:
    name: "linstor-{{ item }}"
    enabled: true
    state: started
  loop: "{{ linstor.hosts[inventory_hostname].roles | default([]) }}"
  when:
    - linstor.hosts[inventory_hostname] is defined
    - item != 'gui'

- name: Check if Linstor node exists
  ansible.builtin.shell: linstor node list | grep -w {{ inventory_hostname }}
  register: linstor_node_check
  ignore_errors: true
  delegate_to: "{{ groups['iaas'][0] }}"

- name: Create Linstor node if missing
  ansible.builtin.shell: |
    linstor node create {{ inventory_hostname }} {{ ansible_host }} --node-type {{ linstor_node_type }}
  args:
    creates: "/var/lib/linstor/nodes/{{ inventory_hostname }}"
  vars:
    linstor_roles: "{{ linstor.hosts[inventory_hostname].roles | default([]) }}"
    linstor_node_type: >-
      {% if 'controller' in linstor_roles and 'satellite' in linstor_roles %}
        combined
      {% elif 'controller' in linstor_roles %}
        controller
      {% elif 'satellite' in linstor_roles %}
        satellite
      {% else %}
        satellite
      {% endif %}
  when: linstor_node_check.rc != 0
  delegate_to: "{{ groups['iaas'][0] }}"
