- name: Post-install tasks for k3s control plane
  hosts: controlplane
  become: true
  tasks:
    - name: Ensure nfs-common & open-iscsi are installed
      ansible.builtin.apt:
        name:
          - nfs-common
          - open-iscsi
        state: present
